#!/usr/bin/python3
import click

from common_flag import CommonFlag, CommonGroup

"""
## common flags

Have an option for a CommandGroup that can be specified
anywhere on it's subcommands.

clicks default model is

    cli --debug cmd1 --cmd1-flag1
    cli --debug cmd2 --cmd2-flag1

or one would need to add the debug flag both subcommands

It would be nice to specify the debug flag anywhere
so both these calls would work

    cli cmd1 --debug --cmd1-flag1
    cli --debug cmd1 --cmd1-flag1

This contradicts clicks design decission. But for common
flags like debug, verbose, quiet it is realy nice.

See also
https://github.com/pallets/click/issues/108
"""

DEBUG = None
QUIET = None

@click.group(cls=CommonGroup)
@click.option('--debug/--no-debug', is_flag=True, default=False, cls=CommonFlag,
              help='turn on debugging')
@click.option('--quiet', '-q', is_flag=True, default=False, cls=CommonFlag,
              help='no info output')
@click.option('--foo', is_flag=True, default=False,
              help='main flag only')
def cli(debug, quiet, foo):
    """any flag that uses the cls CommonOption (debug, quiet) can be put anywhere
    also behind subcommands.
    But the flag foo can only specified for the cli itself"""
    global DEBUG
    global QUIET
    DEBUG = debug
    QUIET = quiet

@cli.command()
def cmd1():
    click.echo(f'cmd1 debug is {DEBUG}, quiet is {QUIET}')

@cli.command()
def cmd2():
    click.echo('cmd2 debug is {DEBUG}, quiet is {QUIET}')

if __name__ == '__main__':
    cli()
